site_name: "ISCC - Schema"
site_description: 'International Standard Content Code - Schema Definitions.'
site_author: 'Titusz Pan'
site_url: 'https://schema.iscc.codes'

# Repository
repo_name: 'iscc/iscc-schema'
repo_url: 'https://github.com/iscc/iscc-schema'
edit_uri: 'edit/main/docs/'

# Copyright
copyright: 'Copyright © 2016-2022 The Authors
| <a href="https://iscc.foundation/privacy">Privacy Policy</a>
| <a href="https://iscc.foundation/cookies">Cookie Policy</a>
| <a href="https://iscc.foundation/imprint">Imprint</a>
| <a href="https://iscc.foundation/disclaimer">Disclaimer</a>'

extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: custom

theme:
  name: material
  custom_dir: docs/overrides
  logo: images/iscc-logo-icon-white.svg
  favicon: images/iscc-logo-icon-black.svg
  language: en
  font:
    text: Readex Pro
    code: JetBrains Mono
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  features:
    - toc.integrate
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand

plugins:
  - search


markdown_extensions:
  - abbr
  - pymdownx.snippets:
      base_path: ["docs/includes"]
      auto_append: ["abbreviations.md"]
  - tables
  - meta
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - footnotes
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.magiclink

nav:
  - Overview: index.md
  - Terms: terms/index.md
  - Schema: schema/index.md
  - Examples: examples/index.md
  - Changelog: changelog.md
