[tool.poetry]
name = "iscc-schema"
version = "0.1.0"
description = "ISCC - Schema Definitions"
authors = ["Titusz <tp@py7.de>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/iscc/iscc-schema"
keywords=["iscc", "identifier", "media", "content", "hash", "blockchain", "similarity"]

[tool.poetry.dependencies]
python = ">=3.6.2,<4.0"
pydantic = "^1.9.0"

[tool.poetry.dev-dependencies]
pytest = "*"
datamodel-code-generator = "^0.11.15"
poethepoet = "^0.11.0"
black = "21.12b0"

[tool.datamodel-codegen]
field-constraints = true
aliases = "iscc_schema/aliases.json"
input = "iscc_schema/models/iscc.yaml"
output = "iscc_schema/schema.py"
field-extra-keys = ["context"]
use-default = true
use-schema-description = true
wrap-string-literal = true
class-name = "ISCC"


[tool.poe.tasks]
build = { cmd = "datamodel-codegen", help = "Build schema module"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
