openapi: 3.0.0
info:
  title: ISCC Generator
  version: 1.5.0
  description: Service for generating ISCC codes for media files.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
- url: https://api.iscc.io/v1.0
tags:
- name: generate
paths:
  /iscc:
    post:
      summary: Create an ISCC for a media asset
      tags:
      - generate
      responses:
        '200':
          $ref: '#/components/responses/GenerateResponse'
      operationId: post-iscc
      description: Create an ISCC Code
      requestBody:
        $ref: '#/components/requestBodies/GenerateRequest'
components:
  schemas: {}
  requestBodies:
    GenerateRequest:
      content:
        multipart/form-data:
          schema:
            type: object
            properties:
              file:
                type: string
                format: binary
                description: The media asset for which to create an ISCC
              name:
                type: string
                description: The title or name of the intangible creation manifested by the
                  identified digital content (used as input for ISCC Meta-Code generation).
              description:
                type: string
                description: Description of the digital content identified by the ISCC (used
                  as input for Meta-Code generation). Any user presentable text string (including
                  Markdown text) indicative of the identity of the referent may be used.
              metadata:
                oneOf:
                - type: object
                  minProperties: 1
                  description: Any object that is JSON/JCS serializable
                - type: string
                  format: byte
                  pattern: ^(?:[A-Za-z\d+/]{4})*(?:[A-Za-z\d+/]{3}=|[A-Za-z\d+/]{2}==)?$
                  description: Base64 encoded file header metadata
                minProperties: 1
                description: Descriptive, industry-sector or use-case specific metadata. Can
                  be any object that is JSON/JCS serializable. If `metadata` is provided it
                  is the sole input for the cryptographic `metahash` calculation. If `metadata`
                  is set to a string it is assumed that it is base64 encoded binary file metadata.
                x-iscc-context: http://purl.org/iscc/terms/#metadata
              embed:
                type: boolean
                description: Embed `name` and `description` metadata into `file` before creating
                  the ISCC. May fail for media types where metadata embedding is not supported.
                default: true
              extract:
                type: boolean
                description: Use extracted metadata for Meta-Code generation.
                default: true
            required:
            - file
      description: Request to generate an ISCC code
  responses:
    GenerateResponse:
      description: Example response
      content:
        application/json:
          schema:
            $ref: ../models/iscc-generator-response.yaml
  securitySchemes: {}
