openapi: 3.0.0
info:
  title: ISCC Generator
  version: 1.5.0
  description: Service for generating ISCC codes for media files.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
- url: https://api.iscc.io/v1.0
tags:
- name: generate
paths:
  /iscc:
    post:
      summary: Create an ISCC for a media asset
      tags:
      - generate
      responses:
        '200':
          $ref: '#/components/responses/GenerateResponse'
      operationId: post-iscc
      description: Create an ISCC Code
      requestBody:
        $ref: '#/components/requestBodies/GenerateRequest'
components:
  schemas: {}
  requestBodies:
    GenerateRequest:
      content:
        multipart/form-data:
          schema:
            allOf:
            - type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The media asset for which to create an ISCC
                url:
                  type: string
                  description: URL of media asset for ISCC creation (use instead of `file`
                    field when apropriate)
                  format: uri
                embed:
                  type: boolean
                  description: Embed `name` and `description` metadata into `file` before
                    creating the ISCC. May fail for media types where metadata embedding is
                    not supported.
                  default: true
                extract:
                  type: boolean
                  description: Use extracted metadata for Meta-Code generation.
                  default: true
                granular:
                  type: boolean
                  description: Create aditional granular fingerprints
                  default: false
                async:
                  type: boolean
                  description: Process file in background and return a task url where the
                    result can be fetched.
                  default: false
            - $ref: ../models/iscc-basic.yaml
      description: Request to generate an ISCC code
  responses:
    GenerateResponse:
      description: Example response
      content:
        application/json:
          schema:
            $ref: ../models/iscc-generator-response.yaml
  securitySchemes: {}
